name: Build fotobox_backend

on:
  push:
    branches:
      - "*"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: docker/setup-qemu-action@v3
      - uses: docker/setup-buildx-action@v3

      - name: Set Tag as Environment Variable
        run: echo "TAG_NAME=${GITHUB_REF##*/}" >> $GITHUB_ENV

      - name: debug
        run: echo "ghcr.io/${{ github.repository_owner }}/fotobox_frontend:${{ env.TAG_NAME }}"

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: './fotobox_backend'
          platforms: linux/amd64,linux/arm64
          push: false
